import type { Metadata } from "next";
import { Tauri } from "next/font/google";
import localFont from "next/font/local";
import "@/app/styles/tailwind.css";
import "@/app/styles/globals.css";
import clsx from "clsx";
import { Viewport } from "next";
import { ReactNode } from "react";
import PrimeProvider from "@/providers/prime";

const tauri = Tauri({ variable: "--tauri", weight: "400", subsets: ["latin"] });

const hHackout = localFont({
  src: "./assets/fonts/Hackout-Eaw5j.otf",
  variable: "--hHackout",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#0d0f12",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={clsx(tauri.variable, tauri.className, hHackout.variable)}>
        <PrimeProvider>{children}</PrimeProvider>
      </body>
    </html>
  );
}
